/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IFYTokenFactoryInterface extends utils.Interface {
  functions: {
    "createFYToken(bytes6,address,address,uint32,string,string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createFYToken",
    values: [BytesLike, string, string, BigNumberish, string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "createFYToken",
    data: BytesLike
  ): Result;

  events: {
    "FYTokenCreated(address,address,uint32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "FYTokenCreated"): EventFragment;
}

export type FYTokenCreatedEvent = TypedEvent<
  [string, string, number],
  { fyToken: string; asset: string; maturity: number }
>;

export type FYTokenCreatedEventFilter = TypedEventFilter<FYTokenCreatedEvent>;

export interface IFYTokenFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IFYTokenFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createFYToken(
      baseId: BytesLike,
      oracle: string,
      baseJoin: string,
      maturity: BigNumberish,
      name: string,
      symbol: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  createFYToken(
    baseId: BytesLike,
    oracle: string,
    baseJoin: string,
    maturity: BigNumberish,
    name: string,
    symbol: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    createFYToken(
      baseId: BytesLike,
      oracle: string,
      baseJoin: string,
      maturity: BigNumberish,
      name: string,
      symbol: string,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "FYTokenCreated(address,address,uint32)"(
      fyToken?: string | null,
      asset?: string | null,
      maturity?: BigNumberish | null
    ): FYTokenCreatedEventFilter;
    FYTokenCreated(
      fyToken?: string | null,
      asset?: string | null,
      maturity?: BigNumberish | null
    ): FYTokenCreatedEventFilter;
  };

  estimateGas: {
    createFYToken(
      baseId: BytesLike,
      oracle: string,
      baseJoin: string,
      maturity: BigNumberish,
      name: string,
      symbol: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createFYToken(
      baseId: BytesLike,
      oracle: string,
      baseJoin: string,
      maturity: BigNumberish,
      name: string,
      symbol: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
