/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IWitchGovInterface extends utils.Interface {
  functions: {
    "limits(bytes6)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "limits", values: [BytesLike]): string;

  decodeFunctionResult(functionFragment: "limits", data: BytesLike): Result;

  events: {};
}

export interface IWitchGov extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IWitchGovInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    limits(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber, number, number, BigNumber]>;
  };

  limits(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<[BigNumber, number, number, BigNumber]>;

  callStatic: {
    limits(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber, number, number, BigNumber]>;
  };

  filters: {};

  estimateGas: {
    limits(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    limits(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
