/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface SafeERC20NamerInterface extends utils.Interface {
  functions: {
    "tokenDecimals(address)": FunctionFragment;
    "tokenName(address)": FunctionFragment;
    "tokenSymbol(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "tokenDecimals",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "tokenName", values: [string]): string;
  encodeFunctionData(functionFragment: "tokenSymbol", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "tokenDecimals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenName", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenSymbol",
    data: BytesLike
  ): Result;

  events: {};
}

export interface SafeERC20Namer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SafeERC20NamerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    tokenDecimals(token: string, overrides?: CallOverrides): Promise<[number]>;

    tokenName(token: string, overrides?: CallOverrides): Promise<[string]>;

    tokenSymbol(token: string, overrides?: CallOverrides): Promise<[string]>;
  };

  tokenDecimals(token: string, overrides?: CallOverrides): Promise<number>;

  tokenName(token: string, overrides?: CallOverrides): Promise<string>;

  tokenSymbol(token: string, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    tokenDecimals(token: string, overrides?: CallOverrides): Promise<number>;

    tokenName(token: string, overrides?: CallOverrides): Promise<string>;

    tokenSymbol(token: string, overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    tokenDecimals(token: string, overrides?: CallOverrides): Promise<BigNumber>;

    tokenName(token: string, overrides?: CallOverrides): Promise<BigNumber>;

    tokenSymbol(token: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    tokenDecimals(
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokenName(
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokenSymbol(
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
